version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/6.7"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/6.8"
    schedule:
      interval: "daily"
