services:
  varnish:
    image: local/varnish
    build: ./6.7
    environment:
      SHOPWARE_BACKEND_HOST: host.docker.internal
      SHOPWARE_ALLOWED_PURGER_IP: '"172.17.0.0"/24'
    ports:
      - "80:80"
    develop:
      watch:
        - path: 6.7/rootfs
          action: rebuild
